name: ZenGuard CI

on:
  push:
    branches:
      - '**'  # Matches any branch
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Add zenguard package
      run: pip install zenguard

    - name: Set API Key
      env:
        ZEN_API_KEY: ${{ secrets.ZEN_API_KEY }}
      run: echo "ZEN_API_KEY=${ZEN_API_KEY}" >> $GITHUB_ENV
      
    - name: Set OpenAI API Key
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> $GITHUB_ENV

    - name: Run E2E tests
      run: python tests/e2e_test.py
      run: python tests/openai_chat_funcionality_e2e_test.py
